### ISSUE TITLE
Add number of new cases for each day

### ISSUE THREAD

**Issue by zetareticoli** [fabiocicerchia/covid19-italy#25]
Actually you can see total and % change only.

**Comment by fabiocicerchia** [comment]
I've just released the functionality show only the new cases day by day.
You can find here: https://covid19.fabiocicerchia.it/

Please do let me know if it is working fine for you, and whether you'd like more functionalities implemented ;)

**Comment by zetareticoli** [comment]
It looks fine. But, how is calculated the % variation? And what is intended for WORST PEAK? 
Example from Rome:
```
2020-03-18: 104 ->  +21%
2020-03-19:  88 ->  +14% WORST PEAK
```
Shouldn't be the previous one?

**Comment by fabiocicerchia** [comment]
You're right, the data's wrong, it was keeping the old formulas based on total cases. I've changed the way it is displayed:

```
COVID-19 NEW CASES IN ROMA

DATE		NEW_CASES	TOTAL_CASES	% INCREASE
2020-02-24	  0		  0
2020-02-25	  3		  3
2020-02-26	  0		  3		   0%
2020-02-27	  0		  3		   0%
2020-02-28	  0		  3		   0%
...
2020-03-18	104		590		 +21%
2020-03-19	 88		678		 +14%
2020-03-20	 77		755		 +11%
2020-03-21	138		893		 +18% WORST PEAK

TOTAL CASES: 893
```

The `WORST PEAK` refers now to the max number of new daily cases in the whole period.
