### ISSUE TITLE
No data displaying

### ISSUE THREAD

**Issue by zetareticoli** [fabiocicerchia/covid19-italy#26]
App says "loading" but it doesn't display anything.

**Comment by fabiocicerchia** [comment]
Could you please provide more details about device, browser and resolution used?
Is it happening at the first loading of the page or after an interaction?

**Comment by zetareticoli** [comment]
It's happening on Safari (both web/mobile). First loading.

**Comment by fabiocicerchia** [comment]
It should be fixed now, thank you for reporting the issue.
